### ISSUE TITLE
Python Package Checklist

### ISSUE THREAD

**Issue by IfyAnene7** [UBC-MDS/524_easysklearn#40]
1. GitHub actions workflow for continuous integration

rubric={mechanics:10}

- [x] Your task here is to make sure the workflow in .github/workflows/build.yml is correctly configured so that at a minimum, it runs the test suite and style checkers on pushes and pull requests to your project’s repository’s deployment branch (typically the main branch). At time of submission, we expect that your project successfully runs this workflow.

A couple of things you might need to change in your .github/workflows/build.yml file:

- [x] Ensure the deployment branch (typically the main branch) is correctly specified on lines 7 & 10

- [x] Ensure that the correct Python version is listed on lines 21 and 24 (it should match the version in your pyproject.toml file)

2. GitHub actions workflow for continuous deployment

rubric={mechanics:10}

- [x] Your task here is to make sure the workflow in .github/workflows/deploy.yml is correctly configured so it runs the test suite, style checkers and deploys to package to test PyPI on pushes to your project’s repository’s deployment branch (typically the main branch). At time of submission, we expect that your project successfully runs this workflow. This should be evidenced by a green release button on your package repository’s README.

A couple of things you might need to change in your .github/workflows/deploy.yml file:

- [x] Ensure the deployment branch (typically the main branch) is correctly specified on lines 7

- [x] Ensure that the correct Python version is listed on line 14 (it should match the version in your pyproject.toml file)

New note: Remove the testing of package versions from the test file (this was added to the cookiecutter template by mistake and interferes with the automated version bumping)

3. Documentation

rubric={reasoning:10}

- [x] Your package documentation should be very clear by the end of this milestone and deployed by ReadTheDocs. All docstrings for all functions should be rendered using the napolean Sphinx extension and readable on ReadTheDocs. Your documentation should also include a demonstration of how to use each function in the package, so that any user with minimal Python expertise would be able to run your package functions and play around with them.

**Comment by IfyAnene7** [comment]
Felt I needed to comment this here to ensure that I've worked on building the documentation:

link: https://readthedocs.org/projects/easysklearn/builds/13233399/
Build #13233399
latest (7bdb94e1df1ef9cc1431e713c91bf3e7fdc2a9a3)
Build completed
